export const GAME_CONFIG = {
  width: 1920,
  height: 1080,
  scale: 0.65,
  main_container_scale_x: 1,
  main_container_scale_y: 1.1,
  PIECE_HEIGHT: 48, // 96 / 2
  PIECE_BOTTOM_HEIGHT: 32,
  PIECE_WIDTH: 64.5, // 129 / 2
  SPACE_X: 5,
  SPACE_Y: 2.5,
  map: [
    {
      id: 0,
      isNormal: false,
      isCorner: true,
      isChance: false,
      isTax: false,
      isStart: true,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'start',
      label: 'start',
      flip: false,
      groupId: 0,
      zIndex: -2
    },
    {
      id: 1,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'veszprem',
      label: 'veszprém',
      flip: false,
      groupId: 1,
      zIndex: -4
    },
    {
      id: 2,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'budapest',
      label: 'budapest',
      flip: false,
      groupId: 1,
      zIndex: -6
    },
    {
      id: 3,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'debrecen',
      label: 'debrecen',
      flip: false,
      groupId: 1,
      zIndex: -8
    },
    {
      id: 4,
      isNormal: false,
      isCorner: false,
      isChance: false,
      isMuseum: true,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'museum',
      label: 'museum',
      flip: false,
      groupId: 0,
      zIndex: -10
    },
    {
      id: 5,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'zurich',
      label: 'Zürich',
      flip: false,
      groupId: 2,
      zIndex: -12
    },
    {
      id: 6,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'paris',
      label: 'Paris',
      flip: false,
      groupId: 2,
      zIndex: -14
    },
    {
      id: 7,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'edinburgh',
      label: 'edinburgh',
      flip: false,
      groupId: 2,
      zIndex: -16
    },
    {
      id: 8,
      isNormal: false,
      isCorner: true,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: true,
      isDoubler: false,
      isErasmus: false,
      name: 'karanten',
      label: 'Karantén',
      flip: false,
      groupId: 2,
      zIndex: -18
    },
    {
      id: 9,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'chicago',
      label: 'chicago',
      flip: true,
      groupId: 3,
      zIndex: -20
    },
    {
      id: 10,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'austin',
      label: 'austin',
      flip: true,
      groupId: 3,
      zIndex: -22
    },
    {
      id: 11,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'princeton',
      label: 'princeton',
      flip: true,
      groupId: 3,
      zIndex: -24
    },
    {
      id: 12,
      isNormal: false,
      isCorner: false,
      isChance: false,
      isMuseum: true,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'museum',
      label: 'museum',
      flip: true,
      groupId: 0,
      zIndex: -26
    },
    {
      id: 13,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'vienna',
      label: 'vienna',
      flip: true,
      groupId: 4,
      zIndex: -28
    },
    {
      id: 14,
      isNormal: false,
      isCorner: false,
      isChance: true,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'esély',
      label: 'esély',
      flip: true,
      groupId: 0,
      zIndex: -30
    },
    {
      id: 15,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'berlin',
      label: 'berlin',
      flip: true,
      groupId: 4,
      zIndex: -32
    },
    {
      id: 16,
      isNormal: false,
      isCorner: true,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: true,
      isErasmus: false,
      name: 'doubler',
      label: 'Talár',
      flip: false,
      groupId: 0,
      zIndex: -34
    },
    {
      id: 17,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'seattle',
      label: 'seattle',
      flip: false,
      groupId: 5,
      zIndex: -32
    },
    {
      id: 18,
      isNormal: false,
      isCorner: false,
      isChance: true,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'esély',
      label: 'esély',
      flip: false,
      groupId: 0,
      zIndex: -30
    },
    {
      id: 19,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'new haven',
      label: 'new haven',
      flip: false,
      groupId: 5,
      zIndex: -28
    },
    {
      id: 20,
      isNormal: false,
      isCorner: false,
      isChance: false,
      isMuseum: true,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'museum',
      label: 'museum',
      flip: false,
      groupId: 0,
      zIndex: -26
    },
    {
      id: 21,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'london',
      label: 'london',
      flip: false,
      groupId: 6,
      zIndex: -24
    },
    {
      id: 22,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'oxford',
      label: 'oxford',
      flip: false,
      groupId: 6,
      zIndex: -22
    },
    {
      id: 23,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'cambridge uk',
      label: 'cambridge uk',
      flip: false,
      groupId: 6,
      zIndex: -20
    },

    {
      id: 24,
      isNormal: false,
      isCorner: true,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: true,
      name: 'erasmus',
      label: 'Erasmus',
      flip: false,
      groupId: 0,
      zIndex: -18
    },

    {
      id: 25,
      isNormal: false,
      isCorner: false,
      isChance: true,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'esély',
      label: 'esély',
      flip: true,
      groupId: 0,
      zIndex: -16
    },
    {
      id: 26,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'berkeley',
      label: 'berkeley',
      flip: true,
      groupId: 7,
      zIndex: -14
    },
    {
      id: 27,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'new york',
      label: 'new york',
      flip: true,
      groupId: 7,
      zIndex: -12
    },
    {
      id: 28,
      isNormal: false,
      isCorner: false,
      isChance: false,
      isMuseum: true,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'museum',
      label: 'museum',
      flip: true,
      groupId: 0,
      zIndex: -10
    },
    {
      id: 29,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'stanford',
      label: 'stanford',
      flip: true,
      groupId: 8,
      zIndex: -8
    },
    {
      id: 30,
      isNormal: false,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: true,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'adó',
      label: 'adó',
      flip: true,
      groupId: 0,
      zIndex: -6
    },
    {
      id: 31,
      isNormal: true,
      isCorner: false,
      isChance: false,
      isMuseum: false,
      isTax: false,
      isStart: false,
      isQuarantaine: false,
      isDoubler: false,
      isErasmus: false,
      name: 'cambridge us',
      label: 'cambridge us',
      flip: true,
      groupId: 8,
      zIndex: -4
    },

  ],
  cards: [
    {
      id: 0,
      PCR: true,
      money: false,
      moneyValue: 0,
      title: 'Negatív PCR teszt',
      desc: 'Nyertél egy negatív PCR tesztet amit legközelebb felhasználhatsz, ha karanténba jutsz.'
    },
    {
      id: 1,
      PCR: false,
      money: true,
      moneyValue: 200_000,
      title: 'Nyeremény',
      desc: 'Olyan jó átlagod lett, hogy 200 000 ft ösztöndíjban részesülsz.'
    },
    {
      id: 2,
      PCR: false,
      money: true,
      moneyValue: -200_000,
      title: 'Minden tárgyól megbuktál',
      desc: 'Sajnos minden tárgyadból megbuktál így 200 000 ft-ot kell fizetned, hogy újra felvehesd őket.'
    },
  ]



}